# Habilitar la consola de la base de datos H2 (Ruta: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:carritodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
